export type Tags = 
| '4-koma' 
| 'Achromatic' 
| 'Achronological Order' 
| 'Acting' 
| 'Advertisement' 
| 'Afterlife' 
| 'Age Gap' 
| 'Age Regression' 
| 'Agender' 
| 'Ahegao' 
| 'Airsoft' 
| 'Aliens' 
| 'Alternate Universe' 
| 'American Football' 
| 'Amnesia' 
| 'Amputation' 
| 'Anachronism' 
| 'Anal Sex' 
| 'Animals' 
| 'Anthology' 
| 'Anti-Hero' 
| 'Archery' 
| 'Armpits' 
| 'Artificial Intelligence' 
| 'Asexual' 
| 'Ashikoki' 
| 'Asphyxiation' 
| 'Assassins' 
| 'Astronomy' 
| 'Athletics' 
| 'Augmented Reality' 
| 'Autobiographical' 
| 'Aviation' 
| 'Badminton' 
| 'Band' 
| 'Bar' 
| 'Baseball' 
| 'Basketball' 
| 'Battle Royale' 
| 'Biographical' 
| 'Bisexual' 
| 'Blackmail' 
| 'Body Horror' 
| 'Body Swapping' 
| 'Bondage' 
| 'Boobjob' 
| 'Boxing' 
| 'Boys Love' 
| 'Bullying' 
| 'Calligraphy' 
| 'Card Battle' 
| 'Cars' 
| 'Centaur' 
| 'CGI' 
| 'Cheerleading' 
| 'Chibi' 
| 'Chimera' 
| 'Chuunibyou' 
| 'Circus' 
| 'Classic Literature' 
| 'College' 
| 'Coming of Age' 
| 'Conspiracy' 
| 'Cosmic Horror' 
| 'Cosplay' 
| 'Crime' 
| 'Crossdressing' 
| 'Crossover' 
| 'Cult' 
| 'Cultivation' 
| 'Cunnilingus' 
| 'Cute Girls Doing Cute Things' 
| 'Cyberpunk' 
| 'Cycling' 
| 'Dancing' 
| 'Dark Skin' 
| 'Death Game' 
| 'Defloration' 
| 'Delinquents' 
| 'Demons' 
| 'Denpa' 
| 'Detective' 
| 'Dinosaurs' 
| 'Dissociative Identities' 
| 'Dragons' 
| 'Drawing' 
| 'Drugs' 
| 'Dullahan' 
| 'Dungeon' 
| 'Dystopian' 
| 'Economics' 
| 'Educational' 
| 'Elf' 
| 'Ensemble Cast' 
| 'Environmental' 
| 'Episodic' 
| 'Ero Guro' 
| 'Espionage' 
| 'Facial' 
| 'Fairy Tale' 
| 'Family Life' 
| 'Fashion' 
| 'Feet' 
| 'Fellatio' 
| 'Female Protagonist' 
| 'Firefighters' 
| 'Fishing' 
| 'Fitness' 
| 'Flash' 
| 'Flat Chest' 
| 'Food' 
| 'Football' 
| 'Foreign' 
| 'Fugitive' 
| 'Full CGI' 
| 'Full Color' 
| 'Futanari' 
| 'Gambling' 
| 'Gangs' 
| 'Gender Bending' 
| 'Ghost' 
| 'Go' 
| 'Goblin' 
| 'Gods' 
| 'Golf' 
| 'Gore' 
| 'Guns' 
| 'Gyaru' 
| 'Handjob' 
| 'Harem' 
| 'Henshin' 
| 'Hikikomori' 
| 'Historical' 
| 'Human Pet' 
| 'Ice Skating' 
| 'Idol' 
| 'Incest' 
| 'Irrumatio' 
| 'Isekai' 
| 'Iyashikei' 
| 'Josei' 
| 'Kaiju' 
| 'Karuta' 
| 'Kemonomimi' 
| 'Kids' 
| 'Kuudere' 
| 'Lacrosse' 
| 'Lactation' 
| 'Language Barrier' 
| 'Large Breasts' 
| 'LGBTQ Issues' 
| 'Lost Civilization' 
| 'Love Triangle' 
| 'Mafia' 
| 'Magic' 
| 'Mahjong' 
| 'Maids' 
| 'Male Protagonist' 
| 'Martial Arts' 
| 'Masturbation' 
| 'Medicine' 
| 'Memory Manipulation' 
| 'Mermaid' 
| 'Meta' 
| 'MILF' 
| 'Military' 
| 'Monster Girl' 
| 'Mopeds' 
| 'Motorcycles' 
| 'Musical' 
| 'Mythology' 
| 'Nakadashi' 
| 'Nekomimi' 
| 'Netorare' 
| 'Netorase' 
| 'Netori' 
| 'Ninja' 
| 'No Dialogue' 
| 'Noir' 
| 'Nudity' 
| 'Nun' 
| 'Office Lady' 
| 'Oiran' 
| 'Ojou-sama' 
| 'Omegaverse' 
| 'Otaku Culture' 
| 'Outdoor' 
| 'Parody' 
| 'Philosophy' 
| 'Photography' 
| 'Pirates' 
| 'Poker' 
| 'Police' 
| 'Politics' 
| 'Post-Apocalyptic' 
| 'POV' 
| 'Pregnant' 
| 'Primarily Adult Cast' 
| 'Primarily Child Cast' 
| 'Primarily Female Cast' 
| 'Primarily Male Cast' 
| 'Prostitution' 
| 'Public Sex' 
| 'Puppetry' 
| 'Rakugo' 
| 'Rape' 
| 'Real Robot' 
| 'Rehabilitation' 
| 'Reincarnation' 
| 'Revenge' 
| 'Reverse Harem' 
| 'Rimjob' 
| 'Robots' 
| 'Rotoscoping' 
| 'Rugby' 
| 'Rural' 
| 'Sadism' 
| 'Samurai' 
| 'Satire' 
| 'Scat' 
| 'School' 
| 'School Club' 
| 'Seinen' 
| 'Sex Toys' 
| 'Shapeshifting' 
| 'Ships' 
| 'Shogi' 
| 'Shoujo' 
| 'Shounen' 
| 'Shrine Maiden' 
| 'Skeleton' 
| 'Slapstick' 
| 'Slavery' 
| 'Software Development' 
| 'Space' 
| 'Space Opera' 
| 'Steampunk' 
| 'Stop Motion' 
| 'Succubus' 
| 'Sumata' 
| 'Super Power' 
| 'Super Robot' 
| 'Superhero' 
| 'Surfing' 
| 'Surreal Comedy' 
| 'Survival' 
| 'Sweat' 
| 'Swimming' 
| 'Swordplay' 
| 'Table Tennis' 
| 'Tanks' 
| 'Teacher' 
| 'Teens Love' 
| 'Tennis' 
| 'Tentacles' 
| 'Terrorism' 
| 'Threesome' 
| 'Time Manipulation' 
| 'Time Skip' 
| 'Tokusatsu' 
| 'Tragedy' 
| 'Trains' 
| 'Triads' 
| 'Tsundere' 
| 'Twins' 
| 'Urban' 
| 'Urban Fantasy' 
| 'Urination' 
| 'Vampire' 
| 'Video Games' 
| 'Vikings' 
| 'Virginity' 
| 'Virtual World' 
| 'Volleyball' 
| 'Vore' 
| 'Voyeur' 
| 'War' 
| 'Werewolf' 
| 'Witch' 
| 'Work' 
| 'Wrestling' 
| 'Writing' 
| 'Wuxia' 
| 'Yakuza' 
| 'Yandere' 
| 'Youkai' 
| 'Yuri' 
| 'Zombie';