// Generated by ChatGPT 5.2
// What this measures (NO real network):
// - Builder pipeline: new MediaBuilder().getAnime(...).title()...request()
// - Manual pipeline: build query string + APIRequest(query) + new Media(raw)
// - (Optional) Build-only: if your MediaBuilder exposes buildQuery/baseQuery access (see notes below)

import test from "node:test";
import assert from "node:assert/strict";
import { performance } from "node:perf_hooks";

import { MediaBuilder, APIRequest, Media } from 'anilist.js'

// --- Fake GraphQL response (matches AniList-ish shape your Media constructor expects)
const fakeResponse = {
  data: {
    Media: {
      id: 21459,
      title: {
        romaji: "My Hero Academia",
        english: "My Hero Academia",
        native: "僕のヒーローアカデミア",
        userPreferred: "My Hero Academia",
      },
      episodes: 138,
      description: "...",
    },
  },
};

// --- Mock fetch globally (so APIRequest() uses this instead of doing real HTTP)
(globalThis as any).fetch = async () =>
  ({
    ok: true,
    status: 200,
    json: async () => fakeResponse,
  } as any);

// --- Simple timing helper
function bench(label: string, iterations: number, fn: () => Promise<void> | void) {
  return (async () => {
    // Warmup (helps JIT a bit; keep small)
    for (let i = 0; i < 200; i++) await fn();

    const t0 = performance.now();
    for (let i = 0; i < iterations; i++) await fn();
    const t1 = performance.now();

    const totalMs = t1 - t0;
    const perIterUs = (totalMs * 1000) / iterations;

    console.log(`${label}: ${totalMs.toFixed(3)}ms total (${perIterUs.toFixed(3)}µs/iter)`);
  })();
}

test("MediaBuilder correctness (mocked fetch)", async () => {
  const media = await new MediaBuilder()
    .getAnime("My Hero Academia")
    .title()
    .episodes()
    .description()
    .request();

  assert.equal(media.id, 21459);
  assert.equal(media.title?.english, "My Hero Academia");
});

test("Overhead: Builder pipeline vs Manual pipeline (100k iterations)", async () => {
  const iterations = 100_000;

  await bench("Builder pipeline overhead", iterations, async () => {
    const media = await new MediaBuilder()
      .getAnime("My Hero Academia")
      .title()
      .episodes()
      .description()
      .request();

    // keep a tiny check to prevent dead-code elimination vibes
    if (media.id !== 21459) throw new Error("wrong id");
  });

  await bench("Manual pipeline overhead", iterations, async () => {
    const query = `query { Media(search: "My Hero Academia", type: ANIME) { id title { romaji english native userPreferred } episodes description } }`;

    const raw = await APIRequest(query);
    const media = new Media(raw);

    if (media.id !== 21459) throw new Error("wrong id");
  });

  // NOTE: If you want, you can add an assertion about relative magnitude,
  // but benchmarks are noisy. Better to just print the numbers.
});

// Optional: if you expose a "build only" method on Builder (recommended for profiling)
// Example implementation idea:
//   build(): string { this.buildQuery(); return this.baseQuery; }
// Then you can uncomment this test and measure builder string construction only.
/*
test("Overhead: Build-only (no APIRequest/json/Media)", async () => {
  const iterations = 200_000;

  await bench("Builder build-only overhead", iterations, async () => {
    const builder = new MediaBuilder()
      .getAnime("My Hero Academia")
      .title()
      .episodes()
      .description();

    const gql = builder.build(); // <-- you'd add this method
    if (!gql.includes("Media")) throw new Error("bad query");
  });

  await bench("Manual string-only overhead", iterations, async () => {
    const query =
      `query { Media(search: "My Hero Academia", type: ANIME) { ` +
      `id title { romaji english native userPreferred } episodes description } }`;

    if (!query.includes("Media")) throw new Error("bad query");
  });
});
*/